name: Workflows Names - run_name_demo1
run-name: Runs Names - run_name_demo2 🚀

on: 
  push:

jobs:
  Jobs-Names-run_name_demo-01:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Run Workflows - run_name_demo"